### PR TITLE
18 tab tag

### PR DESCRIPTION
**Pull request by MaximePikss**

### CODE REVIEW

**Review by RoxaneDrelon — DISMISSED** [review]
SNE

**Review by RoxaneDrelon — DISMISSED** [review]
SNE

**Review by LoicBrassart — CHANGES_REQUESTED** [review]
The `toggleDrawer` function should toggle on *and* off the drawer (that's the meaning of "toggle" :p )
Otherwise, to keep the current behaviour you could call it "openDrawer" (and not change it's code) and create a "closeDrawer" (`setOpen(false)`)

Choose one of those, but I want some coherence in your code

**Review by RoxaneDrelon — APPROVED** [review]
Hoping it's good enough

**Review by LoicBrassart — APPROVED** [review]
Yes! No More Evil!

**Pull request merged**
