### PR TITLE
28 capsule display reduce

### PR DESCRIPTION
**Pull request by Aurelien-Bdr**

### CODE REVIEW

**Review by RoxaneDrelon — DISMISSED** [review]
SnE

**Review by LoicBrassart — DISMISSED** [review]
SnE! 
Recommendation: You should try to record your backend's address in your `.env` file, because it'll stop working when you deploy this to a remote server

**Review by RoxaneDrelon — APPROVED** [review]
Good enough, POI API call will need to be changed quickly to use .env

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
